# services:
#   grafana:
#     image: grafana/grafana:latest
#     ports:
#       - 3000:3000
#     volumes:
#       - ./scripts/grafana/provisioning:/etc/grafana/provisioning
#       - ./scripts/grafana/dashboards:/etc/grafana/demo-dashboards
#       - grafana_data:/var/lib/grafana

#   prometheus:
#     image: prom/prometheus:latest
#     volumes:
#       - ./scripts/prometheus:/etc/prometheus
#       - prometheus_data:/prometheus
#     ports:
#       - "9090:9090"
#     command: 
#       - '--config.file=/etc/prometheus/prometheus.yml'
#       - '--storage.tsdb.retention.time=5m'
#       - '--storage.tsdb.retention.size=10GB'
#     extra_hosts:
#       - "host.docker.internal:host-gateway"

#   fluentbit:
#     image: fluent/fluent-bit:2.1.10
#     ports:
#       - "24224:24224"
#       - "24224:24224/udp"
#     volumes:
#       - ./scripts/fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
#       - ./logs:/app/logs

#   nginx:
#     image: nginx
#     ports:
#       - "80:80"
#     logging:
#       driver: fluentd
#       options:
#         tag: nginx
#         fluentd-sub-second-precision: 'true'

#   loki:
#     image: grafana/loki:2.9.2
#     ports:
#       - "3100:3100"
#     volumes:
#       - ./scripts/loki:/etc/loki
#     command: -config.file=/etc/loki/config.yaml

# volumes:
#   grafana_data:
#   prometheus_data:
  
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./scripts/grafana/provisioning:/etc/grafana/provisioning
      - ./scripts/grafana/dashboards:/etc/grafana/demo-dashboards
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./scripts/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=5m'
      - '--storage.tsdb.retention.size=10GB'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    expose:
      - "16686"
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    command:
      - "--memory.max-traces"
      - "1000"
    restart: always

volumes:
  grafana_data:
  prometheus_data: